### ISSUE TITLE
API 1.6 actions returns list of unimplemented actions

### ISSUE THREAD

**Issue by Maimer** [rightscale/rsc#12]
API 1.6 currently only supports 4 calls:
Instances: index
Deployments: show/index
Images: index

When calling ./rsc cm16 actions, it shows a list of a lot of unimplemented calls.  Additionally, there seems to be a bug on the core side when making an unimplemented call where instead of returning 400 Unimplemented, it returns this:

./rsc cm16 show /api/clouds/6/instances/3I0IE75MSHABN
400 Bad Request
{
  "name": "ValidationError",
  "errors": [
    "Attribute $.params.view: \"default\" is not within the allowed values=[:default, :link] "
  ]
}

**Comment by raphael** [comment]
This is by design of API 1.6 really. Not much we can do in `rsc` other than hard-coding that knowledge which doesn't seem very attractive.
