### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by Maimer** [rightscale/rsc#13]
./rsc --x1 ':has(.val:rel("parent")).href' cm15 show "$instance_href"
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/rightscale/go-jsonselect.func·030(0x209746960, 0x0)
	/home/travis/gopath/src/github.com/rightscale/rsc/Godeps/_workspace/src/github.com/rightscale/go-jsonselect/jsonselect.go:436 +0x951
github.com/rightscale/go-jsonselect.(*Parser).matchNodes(0x209776c80, 0x2095dd800, 0x1, 0xa, 0x20977d600, 0x3b, 0x40, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/rightscale/rsc/Godeps/_workspace/src/github.com/rightscale/go-jsonselect/jsonselect.go:227 +0x415
github.com/rightscale/go-jsonselect.(*Parser).selectorProduction(0x209776c80, 0x209777430, 0x1, 0x2, 0x20977d600, 0x3b, 0x40, 0x1, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/rightscale/rsc/Godeps/_workspace/src/github.com/rightscale/go-jsonselect/jsonselect.go:139 +0x1270
github.com/rightscale/go-jsonselect.(*Parser).evaluateSelector(0x209776c80, 0x7fff5fbff913, 0x1d, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/rightscale/rsc/Godeps/_workspace/src/github.com/rightscale/go-jsonselect/jsonselect.go:41 +0x168
github.com/rightscale/go-jsonselect.(*Parser).GetValues(0x209776c80, 0x7fff5fbff913, 0x1d, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/rightscale/rsc/Godeps/_workspace/src/github.com/rightscale/go-jsonselect/jsonselect.go:68 +0x89
main.(*Displayer).ApplyExtract(0x209735aa0, 0x7fff5fbff913, 0x1d, 0x20972f501, 0x0, 0x0)
	/home/travis/gopath/src/github.com/rightscale/rsc/displayer.go:73 +0x214
main.(*Displayer).ApplySingleExtract(0x209735aa0, 0x7fff5fbff913, 0x1d, 0x0, 0x0)
	/home/travis/gopath/src/github.com/rightscale/rsc/displayer.go:40 +0x6d
main.main()
	/home/travis/gopath/src/github.com/rightscale/rsc/main.go:61 +0x354

goroutine 13 [runnable]:
net/http.(*persistConn).readLoop(0x209399ef0)
	/home/travis/.gimme/versions/go1.4.linux.amd64/src/net/http/transport.go:928 +0x9ce

**Comment by raphael** [comment]
This is fixed in master. Also note that what you were after is probably:
```
rsc --x1 ':has(.rel:val("parent")).href' cm15 show "$instance_href"
```
