### ISSUE TITLE
SS Upload fails: undefined `[]' for nil:NilClass

### ISSUE THREAD

**Issue by dylanmei** [rightscale/rsc#40]
When I run the "Self Service" upload example, with the "Empty CAT" template, the template doesn't upload and the response is

```
failed to create template: invalid response 500 Internal Server Error: Problem:
  An internal error occurred.

Summary:
  Error code: 1nb7gzwzmu76l, Issue: undefined method `[]' for nil:NilClass
```

I am not having any trouble authenticating and listing existing templates.

**Comment by arangamani** [comment]
@dylanmei Can you post the command line you used?

**Comment by dylanmei** [comment]
Here is the program: https://gist.github.com/dylanmei/c60c5be7fa1cd2e4baef
Assuming [test.cat](https://raw.githubusercontent.com/rightscale/rsc/master/ss/examples/upload/test.cat) is in the same directory, it can be run like a script: `go run upload.go`

**Comment by arangamani** [comment]
Can you make sure you have the latest version of rsc? We recently fixed some bugs related to CAT file upload.

**Comment by arangamani** [comment]
We'll look into the error but you can also use the command line to achieve the same
```
rsc ss create collections/12345/templates source=./self.cat.rb
```

**Comment by dylanmei** [comment]
I am using latest code from master.

OAuth doesn't work with Self Service. See: https://gist.github.com/dylanmei/c60c5be7fa1cd2e4baef#file-rsc-ss-upload-go-L17

**Comment by arangamani** [comment]
I see the problem in your code.
```
upload := rsapi.FileUpload{Name: name, Filename: name, Reader: file}
```
`Name` should be `"source"` and not the filename. See the [documentation](http://reference.rightscale.com/selfservice/designer/index.html#/1.0/controller/V1::Controller::Template/create) for reference.

**Comment by dylanmei** [comment]
That works, thanks. Got this from example: https://github.com/rightscale/rsc/blob/master/ss/examples/upload/main.go#L67

I'll submit a pull request to fix your example.

**Comment by arangamani** [comment]
Perfect!

**Comment by raphael** [comment]
Thanks!
