### ISSUE TITLE
Use behind proxy support

### ISSUE THREAD

**Issue by flaccid** [rightscale/rsc#43]
Is it currently possible to use rsc with a http proxy (such as in a corporate environment with no NAT)?
Basically using the `http_proxy` and `https_proxy` env vars if they are set.

**Comment by raphael** [comment]
No that's not currently implemented although it would certainly be a nice feature to add.

**Comment by tve** [comment]
as far as I know all you need to do is set the http_proxy environment variable.

**Comment by flaccid** [comment]
Confirmed unimplemented.
```
$ printenv | grep _proxy
http_proxy=http://foo:3128/
https_proxy=http://foo:3128/

$ curl -v https://google.com/
*   Trying 10.139.158.175...
* Connected to foo (127.0.0.1) port 3128 (#0)
* Establish HTTP proxy tunnel to google.com:443
> CONNECT google.com:443 HTTP/1.1
> Host: google.com:443
> User-Agent: curl/7.41.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
...

$ rsc -r "8ce...c72" --host us-4.rightscale.com cm15 index clouds
[ERROR] Authentication failed: Post https://us-4.rightscale.com/api/oauth2: dial tcp 54.244.88.124:443: operation timed out
```
Use case is behind corporate firewall and in this case the CI needs it to do orchestration with continuous delivery/deployment to VMs and Docker on RightScale but also required for ad-hoc usage on workstations/notebooks.

**Comment by raphael** [comment]
The master branch should now honor HTTP_PROXY and HTTPS_PROXY environment variables.

**Comment by flaccid** [comment]
https://github.com/rightscale/rsc/commit/e9daf48aa370facb7a0b26db6da59d369873e82f https://github.com/rightscale/rsc/commit/b2e65650e39cdca885203efb74e9c50ee01edaa3 https://github.com/rightscale/rsc/commit/0db3f96d65a2e74b2b09d12ea47724400c997c15
Confirmed works (tested with darwin build).

**Comment by raphael** [comment]
Thanks!
