### ISSUE TITLE
rsc setup with oauth

### ISSUE THREAD

**Issue by flaccid** [rightscale/rsc#77]
It would be great if `rsc setup` supported setting the refresh token which could be used automatically when doing `rsc` commands. Perhaps also support so that if an environment variable is set for the refresh token then this would be used in precedence.

Currently afaik `-r` or `-s` is needed with every command if wishing to use oauth. We generally only use oauth particularly when all our uses are SAML (mandated).

**Comment by arangamani** [comment]
Will the [setup](https://github.com/rightscale/rsc#storing-client-credentials) command work for you?

**Comment by flaccid** [comment]
Support for oauth in setup command is first preference. Environment variable, second preference; although it would be totally neat if 'profiles' were supported for the config file (projects like aws-cli do this fairly nicely). Easy way to switch between accounts.

**Comment by arangamani** [comment]
Understood. Pull requests are appreciated by the way 😄

**Comment by flaccid** [comment]
Need to get a little better at golang first :)

**Comment by flaccid** [comment]
Fixed my tests in PR, but last travis run shows fails outside of my remit. Would appreciate a review when possible, thanks.

**Comment by flaccid** [comment]
PR #102 was merged.
